### ISSUE TITLE
What files/scripts should be edited, in order to give the data in ENVI format (.img and .hdr files) ? 

### ISSUE THREAD

**Issue by Potafe** [DegangWang97/IEEE_TGRS_PDBSNet#2]
As at present I have to use this piece of code, to convert my ENVI format data to .mat:
import numpy as np
import scipy.io as sio
from spectral import *

# Load ENVI files
img_file = r"C:\data\AVIRIS-1\image.img"
hdr_file = r"C:\data\AVIRIS-1\image.hdr"

img = envi.open(hdr_file, img_file)
data = img.load()

# Save as .mat file
sio.savemat('AVIRIS', {'data': data})

print('Conversion completed.')

**Comment by DegangWang97** [comment]
You can convert the hyperspectral image and the corresponding ground truth to .mat format and then put the data (.mat [data, map]) into . /data.
