### ISSUE TITLE
Hello again, what should I do to get better performance for images with 300-400 bands?

### ISSUE THREAD

**Issue by Potafe** [DegangWang97/IEEE_TGRS_PDBSNet#3]

**Comment by DegangWang97** [comment]
Hello, thanks for your attention. For our PDBSNet, the PD stride factor and the number of epochs need to be carefully tuned if you want to get better detection performance for different images.

**Comment by Potafe** [comment]
What stride factors, epochs  should be taken in general for these large datasets?

**Comment by DegangWang97** [comment]
For stride factors, generally take values that are comparable to the target size. For epochs, try 3000, or larger epochs if the image size is large.

**Comment by Potafe** [comment]
Ok thanks for the clarification!
